function Arreglo() {

const rojos = [
    { unidad: "01", nombre: "Pedro", cooperacion: 0, estado:1 },
    { unidad: "02", nombre: "Martín", cooperacion: 0, estado:1 },
    { unidad: "03", nombre: "Ramón", cooperacion: 0, estado:1 },
    { unidad: "04", nombre: "Fermín", cooperacion: 0, estado:1 },
    { unidad: "05", nombre: "Juan", cooperacion: 0, estado:1 },
    { unidad: "06", nombre: "Marce", cooperacion: 0, estado:1 },
    { unidad: "07", nombre: "Luis", cooperacion: 0, estado:1 },
    { unidad: "08", nombre: "Humberto", cooperacion: 0, estado:1 },
    { unidad: "09", nombre: "Enrique", cooperacion: 0, estado:1 },
    { unidad: "10", nombre: "Samuel", cooperacion: 0, estado:1 },
    { unidad: "11", nombre: "Víctor", cooperacion: 0, estado:1 },
    { unidad: "12", nombre: "Candido", cooperacion: 0, estado:1 },
    { unidad: "13", nombre: "Paco", cooperacion: 0, estado:1 },
    { unidad: "15", nombre: "Oscar", cooperacion: 0, estado:1 },
    { unidad: "16", nombre: "Heriberto", cooperacion: 0, estado:1 },
    { unidad: "18", nombre: "David", cooperacion: 0, estado:1 },
    { unidad: "19", nombre: "Francisco", cooperacion: 0, estado:1 },
    { unidad: "20", nombre: "Heriberto", cooperacion: 0, estado:1 },
    { unidad: "21", nombre: "Javier", cooperacion: 0, estado:1 },
    { unidad: "22", nombre: "Josue", cooperacion: 0, estado:1 },
    { unidad: "24", nombre: "Hector", cooperacion: 0, estado:1 },
    { unidad: "25", nombre: "Eloy", cooperacion: 0, estado:1 },
    { unidad: "27", nombre: "Daniel", cooperacion: 0, estado:1 },
    { unidad: "28", nombre: "Lobo", cooperacion: 0, estado:1 },
    { unidad: "29", nombre: "Manuel", cooperacion: 0, estado:1 },
    { unidad: "30", nombre: "Sergio", cooperacion: 0, estado:1 },
    { unidad: "31", nombre: "Jose Luis", cooperacion: 0, estado:1 },
    { unidad: "33", nombre: "Juan", cooperacion: 0, estado:1 },
    { unidad: "34", nombre: "Alvaro", cooperacion: 0, estado:1 },
    { unidad: "35", nombre: "Cesar", cooperacion: 0, estado:1 },
    { unidad: "36", nombre: "Filemon", cooperacion: 0, estado:1 },
    { unidad: "37", nombre: "Julio", cooperacion: 0, estado:1 },
    { unidad: "38", nombre: "Rodolfo", cooperacion: 0, estado:1 },
    { unidad: "39", nombre: " ", cooperacion: 0, estado:1 },
    { unidad: "41", nombre: "Juan", cooperacion: 0, estado:1 },
    { unidad: "42", nombre: "Omar", cooperacion: 0, estado:1 },
    { unidad: "43", nombre: "Agustín", cooperacion: 0, estado:1 },
    { unidad: "46", nombre: "Jesus", cooperacion: 0, estado:1 },
    { unidad: "47", nombre: "Octavio", cooperacion: 0, estado:1 },
  ];
  return (rojos)
}

export default Arreglo;