function Arreglo() {

const rojos = [
  { unidad: "01", nombre: "Sergio", cooperacion: 0, estado: 6 },
  { unidad: "02", nombre: "Sergio", cooperacion: 0, estado: 6 },
  { unidad: "03", nombre: "Ramón", cooperacion: 0, estado: 6 },
  { unidad: "04", nombre: "Fermín", cooperacion: 0, estado: 6 },
  { unidad: "05", nombre: "Juan", cooperacion: 0, estado: 6 },
  { unidad: "06", nombre: "Avila", cooperacion: 0, estado: 6 },
  { unidad: "07", nombre: "Norberto", cooperacion: 0, estado: 6 },
  { unidad: "08", nombre: "Humberto", cooperacion: 0, estado: 6 },
  { unidad: "09", nombre: "Enrique", cooperacion: 0, estado: 6 },
  { unidad: "10", nombre: "Noe", cooperacion: 0, estado: 6 },
  { unidad: "11", nombre: "Víctor", cooperacion: 0, estado: 6 },
  { unidad: "12", nombre: "Candido", cooperacion: 0, estado: 6 },
  { unidad: "13", nombre: "Paco", cooperacion: 0, estado: 6 },
  { unidad: "14", nombre: "Daniel", cooperacion: 0, estado: 6 },
  { unidad: "15", nombre: "Oscar", cooperacion: 0, estado: 6 },
  { unidad: "16", nombre: "Jose Luis", cooperacion: 0, estado: 6 },
  { unidad: "18", nombre: "Samuel", cooperacion: 0, estado: 6 },
  { unidad: "19", nombre: "Francisco", cooperacion: 0, estado: 6 },
  { unidad: "20", nombre: "Heriberto", cooperacion: 0, estado: 6 },
  { unidad: "21", nombre: "Javier", cooperacion: 0, estado: 6 },
  { unidad: "22", nombre: "Daniel", cooperacion: 0, estado: 6 },
  { unidad: "24", nombre: "Bolillo", cooperacion: 0, estado: 6 },
  { unidad: "25", nombre: "Aldo", cooperacion: 0, estado: 6 },
  { unidad: "27", nombre: "Daniel", cooperacion: 0, estado: 6 },
  { unidad: "28", nombre: "Lobo", cooperacion: 0, estado: 6 },
  { unidad: "29", nombre: "Filos", cooperacion: 0, estado: 6 },
  { unidad: "30", nombre: "Alex", cooperacion: 0, estado: 6 },
  { unidad: "31", nombre: "Jose Luis", cooperacion: 0, estado: 6 },
  { unidad: "33", nombre: "Mayormono", cooperacion: 0, estado: 6 },
  { unidad: "34", nombre: "Alvaro", cooperacion: 0, estado: 6 },
  { unidad: "35", nombre: "Tiquio", cooperacion: 0, estado: 6 },
  { unidad: "36", nombre: "Rene", cooperacion: 0, estado: 6 },
  { unidad: "37", nombre: "Pedro", cooperacion: 0, estado: 6 },
  { unidad: "38", nombre: "Raymundo", cooperacion: 0, estado: 6 },
  { unidad: "39", nombre: "Adan", cooperacion: 0, estado: 6 },
  { unidad: "40", nombre: "Manuel", cooperacion: 0, estado: 6 },
  { unidad: "41", nombre: "Alejandro", cooperacion: 0, estado: 6 },
  { unidad: "42", nombre: "Tyson", cooperacion: 0, estado: 6 },
  { unidad: "43", nombre: "Agustín", cooperacion: 0, estado: 6 },
  { unidad: "46", nombre: "Fausto", cooperacion: 0, estado: 6 },
  { unidad: "47", nombre: "Eloy", cooperacion: 0, estado: 6 },
  ];
  return (rojos)
}

export default Arreglo;